import { Layouts } from "react-grid-layout";

export const defaultLayouts: Layouts = {
    "lg": [{
        "w": 3,
        "h": 3,
        "x": 2,
        "y": 0,
        "minW": 1,
        "minH": 2,
        "maxW": 3,
        "maxH": 5,
        "i": "My Projects",
    },
    {
        "w": 2,
        "h": 2,
        "x": 0,
        "y": 0,
        "minW": 1,
        "minH": 2,
        "maxW": 2,
        "maxH": 3,
        "i": "About Me",
    },
    {
        "w": 2,
        "h": 3,
        "x": 3,
        "y": 3,
        "minW": 1,
        "minH": 3,
        "maxW": 3,
        "maxH": 4,
        "i": "Chat",
    },
    {
        "w": 3,
        "h": 3,
        "x": 0,
        "y": 3,
        "minW": 1,
        "minH": 2,
        "maxW": 8,
        "maxH": 4,
        "i": "My Work",
    },
    {
        "w": 2,
        "h": 1,
        "x": 0,
        "y": 2,
        "minW": 1,
        "minH": 1,
        "maxW": 8,
        "maxH": 1,
        "i": "Contact",
    }],
    "md": [{
        "w": 1,
        "h": 3,
        "x": 1,
        "y": 0,
        "minW": 1,
        "minH": 2,
        "maxW": 4,
        "maxH": 5,
        "i": "My Projects",
    },
    {
        "w": 2,
        "h": 3,
        "x": 0,
        "y": 0,
        "i": "About Me",
    },
    {
        "w": 2,
        "h": 3,
        "x": 0,
        "y": 3,
        "minW": 2,
        "minH": 3,
        "maxW": 4,
        "maxH": 4,
        "i": "Chat",
    },
    {
        "w": 4,
        "h": 2,
        "x": 0,
        "y": 6,
        "i": "My Work",
    },
    {
        "w": 4,
        "h": 1,
        "x": 0,
        "y": 8,
        "i": "Contact",
    }],
    "sm": [{
        "w": 1,
        "h": 5,
        "x": 0,
        "y": 2,
        "i": "My Projects",
    },
    {
        "w": 1,
        "h": 2,
        "x": 0,
        "y": 0,
        "i": "About Me",
    },
    {
        "w": 1,
        "h": 3,
        "x": 0,
        "y": 7,
        "i": "Chat",
    },
    {
        "w": 1,
        "h": 3,
        "x": 0,
        "y": 10,
        "i": "My Work",
    },
    {
        "w": 1,
        "h": 1,
        "x": 0,
        "y": 13,
        "i": "Contact",
    }]
}